# Generated by Django 4.2.5 on 2023-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('state', models.CharField(max_length=15, verbose_name='State')),
                ('district', models.CharField(max_length=15, verbose_name='District')),
            ],
        ),
    ]
