# Generated by Django 4.2.5 on 2023-09-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasha_mukti_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='addiction_type',
            new_name='addiction',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(default=0, max_length=6, verbose_name='pin_code'),
            preserve_default=False,
        ),
    ]
